# Generated by Django 2.1.7 on 2023-03-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tb_user',
        ),
    ]
