# Generated by Django 2.1.7 on 2023-03-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230321_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default='nomail@nomail.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
