# Generated by Django 2.1.7 on 2023-03-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230324_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='lmln828@naver.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
