# Generated by Django 2.1.7 on 2023-02-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(default=150000, verbose_name='상품재고'),
            preserve_default=False,
        ),
    ]
